version: "3.9"

services:
  api:
    build: .
    container_name: gov-ai-api
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      # Mount for development (optional - remove in production)
      - ./app:/app:ro
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: gov-ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: unless-stopped
    profiles:
      - production