"""
Initialize Supabase table for Israeli Government Decisions
Run this script to create the required table structure in Supabase.
"""

import os
from dotenv import load_dotenv
from supabase import create_client

# Load environment variables
load_dotenv()

# SQL for creating the table
CREATE_TABLE_SQL = """
-- Create israeli_government_decisions table
CREATE TABLE IF NOT EXISTS israeli_government_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_number TEXT,
    title TEXT NOT NULL,
    description TEXT,
    date DATE,
    ministry TEXT,
    status TEXT,
    category TEXT,
    tags TEXT[],
    full_text TEXT,
    attachments JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_decisions_date ON israeli_government_decisions(date);
CREATE INDEX IF NOT EXISTS idx_decisions_ministry ON israeli_government_decisions(ministry);
CREATE INDEX IF NOT EXISTS idx_decisions_status ON israeli_government_decisions(status);
CREATE INDEX IF NOT EXISTS idx_decisions_category ON israeli_government_decisions(category);

-- Enable Row Level Security
ALTER TABLE israeli_government_decisions ENABLE ROW LEVEL SECURITY;

-- Create policy for read access (adjust as needed)
CREATE POLICY "Enable read access for all users" ON israeli_government_decisions
    FOR SELECT USING (true);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_israeli_government_decisions_updated_at
    BEFORE UPDATE ON israeli_government_decisions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
"""

# Sample data for testing
SAMPLE_DATA = [
    {
        "decision_number": "2023-001",
        "title": "הקמת ועדה לאומית לחדשנות טכנולוגית",
        "description": "החלטה על הקמת ועדה לאומית לקידום חדשנות טכנולוגית במגזר הציבורי",
        "date": "2023-01-15",
        "ministry": "משרד החדשנות, המדע והטכנולוגיה",
        "status": "אושר",
        "category": "טכנולוגיה וחדשנות",
        "tags": ["חדשנות", "טכנולוגיה", "מגזר ציבורי"],
        "full_text": "הממשלה מחליטה על הקמת ועדה לאומית שתפקידה לקדם שימוש בטכנולוגיות חדשניות במגזר הציבורי..."
    },
    {
        "decision_number": "2023-002",
        "title": "תוכנית לאומית לצמצום פערים דיגיטליים",
        "description": "אישור תוכנית רב-שנתית לצמצום פערים דיגיטליים באוכלוסיות מוחלשות",
        "date": "2023-02-20",
        "ministry": "משרד הרווחה והביטחון החברתי",
        "status": "אושר",
        "category": "רווחה וחברה",
        "tags": ["פערים דיגיטליים", "רווחה", "שוויון הזדמנויות"],
        "full_text": "במטרה לצמצם פערים דיגיטליים, הממשלה מאשרת תוכנית לאומית שתכלול..."
    },
    {
        "decision_number": "2023-003",
        "title": "הרחבת תוכנית החינוך הטכנולוגי",
        "description": "הרחבת תוכנית החינוך הטכנולוגי לכלול מקצועות בינה מלאכותית ומדעי הנתונים",
        "date": "2023-03-10",
        "ministry": "משרד החינוך",
        "status": "בתהליך",
        "category": "חינוך",
        "tags": ["חינוך", "טכנולוגיה", "בינה מלאכותית"],
        "full_text": "משרד החינוך יפעל להרחבת תוכנית הלימודים הטכנולוגית..."
    }
]

def main():
    """Initialize Supabase table and insert sample data"""
    print("🚀 Initializing Supabase table...")
    
    try:
        # Get credentials
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
        
        if not url or not key:
            print("❌ Missing Supabase credentials in .env file")
            return
        
        # Create client
        supabase = create_client(url, key)
        
        print("📋 Table creation SQL ready.")
        print("⚠️  IMPORTANT: You need to run the SQL above in your Supabase SQL editor")
        print("Go to: Your Supabase Dashboard > SQL Editor > New Query")
        print("\n" + "="*50)
        print(CREATE_TABLE_SQL)
        print("="*50 + "\n")
        
        # Check if table exists
        try:
            response = supabase.table("israeli_government_decisions").select("count").execute()
            print(f"✅ Table exists with {response.count} records")
            
            if response.count == 0:
                print("📝 Inserting sample data...")
                for item in SAMPLE_DATA:
                    supabase.table("israeli_government_decisions").insert(item).execute()
                print(f"✅ Inserted {len(SAMPLE_DATA)} sample records")
            
        except Exception as e:
            print(f"⚠️  Table might not exist yet. Error: {str(e)}")
            print("Please run the SQL above in Supabase first.")
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")

if __name__ == "__main__":
    main()